"""
Live tab: controller diagram whose buttons / sticks / triggers light up
in real-time from StateBridge snapshots.

Two render modes:
  1. Image mode  — assets/controller.png + assets/controller_layout.json
                   (generated by scripts/generate_controller_art.py)
  2. Vector mode — pure Canvas primitives (fallback; always works)
"""
import json
import logging
import tkinter as tk
from pathlib import Path
from tkinter import ttk
from typing import Optional

from config.settings import (
    AXIS_LX, AXIS_LY, AXIS_RX, AXIS_RY, AXIS_LT, AXIS_RT,
    BUTTON_A, BUTTON_B, BUTTON_X, BUTTON_Y, BUTTON_LB, BUTTON_RB,
    BUTTON_BACK, BUTTON_START, BUTTON_LSTICK, BUTTON_RSTICK, BUTTON_GUIDE,
)
from ui.dashboard import theme as T
from ui.state_bridge import Snapshot, StateBridge

logger = logging.getLogger(__name__)

_ASSETS = Path(__file__).resolve().parent.parent.parent / "assets"
_IMG_PATH = _ASSETS / "controller.png"
_LAYOUT_PATH = _ASSETS / "controller_layout.json"

# Face-button positions relative to canvas center (dx, dy, label)
_FACE = [
    (BUTTON_Y, 130, -30, "Y", "#f5d847"),
    (BUTTON_X, 108,  -8, "X", "#4a9eff"),
    (BUTTON_B, 152,  -8, "B", "#ff5c6b"),
    (BUTTON_A, 130,  14, "A", "#4aff7a"),
]
# Stick "base" positions (center)
_LSTICK = (-90, 0)
_RSTICK = ( 60, 30)
# Shoulder buttons
_LB = (-140, -60, "LB")
_RB = ( 140, -60, "RB")
# Center cluster
_BACK  = (-30, -12, "⊟")
_START = ( 30, -12, "≡")
_GUIDE = (  0, -40, "◯")
# Triggers
_LT_RECT = (-170, -90, -130, -70)
_RT_RECT = ( 130, -90,  170, -70)
# D-pad cross
_DPAD = (-60, 30)   # center


class LiveTab(ttk.Frame):
    def __init__(self, master: tk.Misc, bridge: StateBridge) -> None:
        super().__init__(master, style="Dash.TFrame")
        self._bridge = bridge

        # Toolbar
        bar = ttk.Frame(self, style="Dash.TFrame")
        bar.pack(fill="x", padx=8, pady=(8, 4))
        ttk.Button(bar, text="Toggle Mode", style="Dash.TButton",
                   command=self._toggle_mode).pack(side="left")
        self._hz_var = tk.StringVar(value="0 Hz")
        ttk.Label(bar, textvariable=self._hz_var,
                  style="DashMuted.TLabel").pack(side="right")

        # Canvas
        self._canvas = tk.Canvas(self, bg=T.BG_SUNKEN, highlightthickness=0, bd=0)
        self._canvas.pack(fill="both", expand=True, padx=8, pady=(4, 8))
        self._canvas.bind("<Configure>", lambda _e: self._redraw_static())

        self._ids: dict = {}  # named item ids for fast updates
        self._last_size = (0, 0)

        # Image-mode state
        self._layout: Optional[dict] = None
        self._img_src = None      # PIL.Image
        self._img_tk = None       # ImageTk.PhotoImage (kept alive on self)
        self._image_mode = self._try_load_image_assets()
        if self._image_mode:
            logger.info("Live tab: image mode (assets/controller.png)")
        else:
            logger.info("Live tab: vector mode")

    # ---- public: called each poll by the dashboard ----
    def update_snapshot(self, snap: Snapshot) -> None:
        if self._last_size != (self._canvas.winfo_width(), self._canvas.winfo_height()):
            self._redraw_static()
        self._update_dynamic(snap)
        self._hz_var.set(f"{snap.tick_hz:.0f} Hz")

    # ---- asset loader ----
    def _try_load_image_assets(self) -> bool:
        if not (_IMG_PATH.exists() and _LAYOUT_PATH.exists()):
            return False
        try:
            from PIL import Image  # lazy — PIL ships with pystray already
            self._img_src = Image.open(_IMG_PATH).convert("RGBA")
            self._layout = json.loads(_LAYOUT_PATH.read_text(encoding="utf-8"))
            return True
        except Exception:
            logger.exception("Failed to load controller image assets")
            self._img_src = None
            self._layout = None
            return False

    # ---- static geometry ----
    def _redraw_static(self) -> None:
        self._canvas.delete("all")
        self._ids.clear()
        w = max(self._canvas.winfo_width(), 1)
        h = max(self._canvas.winfo_height(), 1)
        self._last_size = (w, h)
        cx, cy = w // 2, h // 2

        if self._image_mode and self._img_src is not None:
            self._redraw_image_mode(w, h)
            return

        # Body outline
        self._canvas.create_oval(cx-210, cy-80, cx+210, cy+100,
            outline=T.BORDER, width=2)

        # Triggers (will fill dynamically)
        for key, rect in (("lt", _LT_RECT), ("rt", _RT_RECT)):
            x1, y1, x2, y2 = rect
            self._canvas.create_rectangle(cx+x1, cy+y1, cx+x2, cy+y2,
                outline=T.BORDER, width=1)
            self._ids[f"{key}_fill"] = self._canvas.create_rectangle(
                cx+x1, cy+y2, cx+x2, cy+y2,  # zero-height, grows up
                fill=T.ACCENT, outline="")
            self._ids[f"{key}_rect"] = rect

        # Shoulders
        for (key, (bx, by, label)) in (("lb", _LB), ("rb", _RB)):
            self._ids[f"{key}_bg"] = self._canvas.create_rectangle(
                cx+bx-22, cy+by-8, cx+bx+22, cy+by+8,
                fill=T.BG_ELEVATED, outline=T.BORDER)
            self._canvas.create_text(cx+bx, cy+by, text=label,
                fill=T.FG_MUTED, font=T.FONT_LABEL)

        # Face buttons
        for btn_idx, dx, dy, label, color in _FACE:
            self._ids[f"btn_{btn_idx}_bg"] = self._canvas.create_oval(
                cx+dx-12, cy+dy-12, cx+dx+12, cy+dy+12,
                fill=T.BG_ELEVATED, outline=T.BORDER)
            self._canvas.create_text(cx+dx, cy+dy, text=label,
                fill=color, font=T.FONT_BOLD)

        # Center cluster (Back, Start, Guide)
        for (key, (dx, dy, label)) in (("back", _BACK), ("start", _START), ("guide", _GUIDE)):
            self._ids[f"{key}_bg"] = self._canvas.create_oval(
                cx+dx-9, cy+dy-9, cx+dx+9, cy+dy+9,
                fill=T.BG_ELEVATED, outline=T.BORDER)
            self._canvas.create_text(cx+dx, cy+dy, text=label,
                fill=T.FG_MUTED, font=T.FONT_LABEL)

        # D-pad (4 triangles)
        dx, dy = _DPAD
        size = 16
        coords = {
            "up":    (cx+dx, cy+dy-size, cx+dx-size//2, cy+dy, cx+dx+size//2, cy+dy),
            "down":  (cx+dx, cy+dy+size, cx+dx-size//2, cy+dy, cx+dx+size//2, cy+dy),
            "left":  (cx+dx-size, cy+dy, cx+dx, cy+dy-size//2, cx+dx, cy+dy+size//2),
            "right": (cx+dx+size, cy+dy, cx+dx, cy+dy-size//2, cx+dx, cy+dy+size//2),
        }
        for d, c in coords.items():
            self._ids[f"dpad_{d}"] = self._canvas.create_polygon(
                c, fill=T.BG_ELEVATED, outline=T.BORDER)

        # Sticks — outer ring + moving dot
        for (key, (sx, sy)) in (("lstick", _LSTICK), ("rstick", _RSTICK)):
            self._canvas.create_oval(cx+sx-34, cy+sy-34, cx+sx+34, cy+sy+34,
                outline=T.BORDER, width=1)
            self._ids[f"{key}_dot"] = self._canvas.create_oval(
                cx+sx-8, cy+sy-8, cx+sx+8, cy+sy+8,
                fill=T.FG_MUTED, outline="")
            self._ids[f"{key}_center"] = (cx+sx, cy+sy)

    # ---- image-mode static render ----
    def _redraw_image_mode(self, w: int, h: int) -> None:
        from PIL import ImageTk
        iw, ih = self._img_src.size
        scale = min(w / iw, h / ih)
        rw, rh = max(1, int(iw * scale)), max(1, int(ih * scale))
        ox, oy = (w - rw) // 2, (h - rh) // 2
        img = self._img_src.resize((rw, rh))
        self._img_tk = ImageTk.PhotoImage(img)
        self._canvas.create_image(ox, oy, anchor="nw", image=self._img_tk)

        self._ids["_img_box"] = (ox, oy, rw, rh)
        L = self._layout or {}

        def circle(key: str, nx: float, ny: float, nr: float, color: str = T.ACCENT):
            cx = ox + nx * rw
            cy = oy + ny * rh
            r  = nr * rw
            self._ids[key] = self._canvas.create_oval(
                cx - r, cy - r, cx + r, cy + r,
                outline=color, width=2, fill="")

        def rectangle(key: str, nx: float, ny: float, nw: float, nh: float,
                      color: str = T.ACCENT):
            cx = ox + nx * rw
            cy = oy + ny * rh
            x1 = cx - (nw * rw) / 2
            y1 = cy - (nh * rh) / 2
            x2 = cx + (nw * rw) / 2
            y2 = cy + (nh * rh) / 2
            self._ids[key] = self._canvas.create_rectangle(
                x1, y1, x2, y2, outline=color, width=2, fill="")

        # Face buttons
        for name, btn_idx, color in (("A", BUTTON_A, "#4aff7a"),
                                     ("B", BUTTON_B, "#ff5c6b"),
                                     ("X", BUTTON_X, "#4a9eff"),
                                     ("Y", BUTTON_Y, "#f5d847")):
            fb = L.get("face_buttons", {}).get(name)
            if fb:
                circle(f"btn_{btn_idx}", fb["x"], fb["y"], fb["r"], color)

        # Shoulders
        for name, btn_idx in (("LB", BUTTON_LB), ("RB", BUTTON_RB)):
            s = L.get("shoulders", {}).get(name)
            if s:
                rectangle(f"btn_{btn_idx}", s["x"], s["y"], s["w"], s["h"])

        # Triggers
        for name, axis in (("LT", AXIS_LT), ("RT", AXIS_RT)):
            t = L.get("triggers", {}).get(name)
            if t:
                rectangle(f"trigger_{axis}", t["x"], t["y"], t["w"], t["h"], T.WARN)

        # Center cluster
        for name, btn_idx in (("BACK", BUTTON_BACK), ("START", BUTTON_START),
                               ("GUIDE", BUTTON_GUIDE)):
            c = L.get("center", {}).get(name)
            if c:
                circle(f"btn_{btn_idx}", c["x"], c["y"], c["r"])

        # Sticks
        for name, click_btn in (("L", BUTTON_LSTICK), ("R", BUTTON_RSTICK)):
            s = L.get("sticks", {}).get(name)
            if s:
                circle(f"stick_{click_btn}_ring", s["x"], s["y"], s["r"])
                # inner dot (updated dynamically)
                cxp = ox + s["x"] * rw
                cyp = oy + s["y"] * rh
                rp  = 0.015 * rw
                self._ids[f"stick_{click_btn}_dot"] = self._canvas.create_oval(
                    cxp - rp, cyp - rp, cxp + rp, cyp + rp,
                    fill=T.ACCENT, outline="")
                self._ids[f"stick_{click_btn}_meta"] = (cxp, cyp, s["r"] * rw * 0.9)

        # D-pad
        d = L.get("dpad")
        if d:
            circle("dpad_hint", d["x"], d["y"], d["r"])

    # ---- dynamic updates ----
    def _update_dynamic(self, snap: Snapshot) -> None:
        if not self._ids:
            return
        if self._image_mode:
            self._update_dynamic_image(snap)
            return

        # Face buttons
        for btn_idx, *_rest in _FACE:
            pressed = snap.buttons.get(btn_idx, False)
            self._canvas.itemconfig(self._ids[f"btn_{btn_idx}_bg"],
                fill=T.PRESSED if pressed else T.BG_ELEVATED)

        # Shoulders
        for key, btn_idx in (("lb", BUTTON_LB), ("rb", BUTTON_RB)):
            pressed = snap.buttons.get(btn_idx, False)
            self._canvas.itemconfig(self._ids[f"{key}_bg"],
                fill=T.PRESSED if pressed else T.BG_ELEVATED)

        # Center cluster
        for key, btn_idx in (("back", BUTTON_BACK), ("start", BUTTON_START), ("guide", BUTTON_GUIDE)):
            pressed = snap.buttons.get(btn_idx, False)
            self._canvas.itemconfig(self._ids[f"{key}_bg"],
                fill=T.PRESSED if pressed else T.BG_ELEVATED)

        # D-pad
        hx, hy = snap.hat
        self._canvas.itemconfig(self._ids["dpad_up"],    fill=T.PRESSED if hy ==  1 else T.BG_ELEVATED)
        self._canvas.itemconfig(self._ids["dpad_down"],  fill=T.PRESSED if hy == -1 else T.BG_ELEVATED)
        self._canvas.itemconfig(self._ids["dpad_left"],  fill=T.PRESSED if hx == -1 else T.BG_ELEVATED)
        self._canvas.itemconfig(self._ids["dpad_right"], fill=T.PRESSED if hx ==  1 else T.BG_ELEVATED)

        # Sticks
        for key, ax, ay, click_btn in (
            ("lstick", AXIS_LX, AXIS_LY, BUTTON_LSTICK),
            ("rstick", AXIS_RX, AXIS_RY, BUTTON_RSTICK),
        ):
            vx = snap.axes.get(ax, 0.0)
            vy = snap.axes.get(ay, 0.0)
            base_x, base_y = self._ids[f"{key}_center"]
            x = base_x + vx * 26
            y = base_y + vy * 26
            self._canvas.coords(self._ids[f"{key}_dot"],
                x-8, y-8, x+8, y+8)
            clicked = snap.buttons.get(click_btn, False)
            self._canvas.itemconfig(self._ids[f"{key}_dot"],
                fill=T.PRESSED if clicked else T.ACCENT)

        # Triggers (normalize SDL2 -1..+1 to 0..1)
        for key, axis in (("lt", AXIS_LT), ("rt", AXIS_RT)):
            raw = snap.axes.get(axis, -1.0)
            val = max(0.0, min(1.0, (raw + 1.0) / 2.0))
            x1, y1, x2, y2 = self._ids[f"{key}_rect"]
            w = max(self._canvas.winfo_width(), 1)
            h = max(self._canvas.winfo_height(), 1)
            cx, cy = w // 2, h // 2
            height = (y2 - y1) * val
            self._canvas.coords(self._ids[f"{key}_fill"],
                cx+x1, cy+y2-height, cx+x2, cy+y2)

    def _toggle_mode(self) -> None:
        self._bridge.switch_mode()

    # ---- image-mode dynamic ----
    def _update_dynamic_image(self, snap: Snapshot) -> None:
        """Re-color overlay rings; move stick dots; fill trigger rects."""
        def set_ring(key, pressed: bool, on_color=T.PRESSED):
            iid = self._ids.get(key)
            if iid is None:
                return
            self._canvas.itemconfig(iid,
                outline=on_color if pressed else T.ACCENT,
                width=3 if pressed else 2)

        for btn_idx in (BUTTON_A, BUTTON_B, BUTTON_X, BUTTON_Y,
                        BUTTON_LB, BUTTON_RB,
                        BUTTON_BACK, BUTTON_START, BUTTON_GUIDE):
            set_ring(f"btn_{btn_idx}", snap.buttons.get(btn_idx, False))

        # Sticks
        for click_btn, ax, ay in ((BUTTON_LSTICK, AXIS_LX, AXIS_LY),
                                   (BUTTON_RSTICK, AXIS_RX, AXIS_RY)):
            meta = self._ids.get(f"stick_{click_btn}_meta")
            dot  = self._ids.get(f"stick_{click_btn}_dot")
            if not meta or not dot:
                continue
            cxp, cyp, reach = meta
            vx = snap.axes.get(ax, 0.0)
            vy = snap.axes.get(ay, 0.0)
            dx = cxp + vx * reach
            dy = cyp + vy * reach
            rp = reach * 0.15
            self._canvas.coords(dot, dx - rp, dy - rp, dx + rp, dy + rp)
            clicked = snap.buttons.get(click_btn, False)
            self._canvas.itemconfig(dot,
                fill=T.PRESSED if clicked else T.ACCENT)

        # Triggers — fill overlay rectangle proportional to travel
        for axis in (AXIS_LT, AXIS_RT):
            iid = self._ids.get(f"trigger_{axis}")
            if iid is None:
                continue
            raw = snap.axes.get(axis, -1.0)
            val = max(0.0, min(1.0, (raw + 1.0) / 2.0))
            self._canvas.itemconfig(iid,
                fill=T.WARN if val > 0.05 else "",
                stipple="gray25" if val > 0.05 else "")
            # Outline thickness reflects travel
            self._canvas.itemconfig(iid, width=1 + int(3 * val))

        # D-pad — pulse the hint ring when any direction held
        hx, hy = snap.hat
        active = (hx, hy) != (0, 0)
        set_ring("dpad_hint", active, on_color=T.PRESSED)
